#!/bin/bash
echo "🚀 Fast Matrix Multiplication Demo"
echo "=================================="
echo ""
echo "Using smaller matrices for quick demonstration..."
echo "Matrix size: 3×100 × 100×100 = 3×100"
echo ""
echo "Starting execution..."
./scheduler 3 100 100 demo_in1.txt demo_in2.txt demo_out.txt
echo ""
echo "✅ Execution completed!"
echo ""
echo "📊 Performance Results:"
echo "======================"
echo "P1 Performance Data:"
cat values_P1.csv 2>/dev/null || echo "No P1 data generated yet"
echo ""
echo "P2 Performance Data:"  
cat values_P2.csv 2>/dev/null || echo "No P2 data generated yet"
echo ""
echo "📁 Generated files:"
ls -la demo_out.txt values*.csv 2>/dev/null || echo "No output files yet"
echo ""
echo "�� Demo complete! Check the generated files."
